sudo: required
services:
    - docker

before_install:
    - docker build -t jackcodes/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jackcodes/react-test npm test -- --coverage

after_success:
    - docker build -t jackscode/multi-client ./client
    - docker build -t jackscode/multi-nginx ./nginx
    - docker build -t jackscode/multi-server ./server
    - docker build -t jackscode/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jackscode/multi-client
    - docker push jackscode/multi-nginx
    - docker push jackscode/multi-server
    - docker push jackscode/multi-worker

deploy:
    label: "0.0.2"
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Multi-Docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-976520447513"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
